import java.io.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Scrabble testScrabble = new Scrabble();
        Console myConsole = System.console();

        System.out.println("Enter a word: ");
        String scrabbleWord = myConsole.readLine();
        String scrabbleName = scrabbleWord.toUpperCase();
        int score = testScrabble.calculateScore(scrabbleName);
        System.out.println(score);


    }

}
