
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ScrabbleTest {

    @Test
    public void calculateScore_returnScoreForLetterValue_1() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 1;
        assertEquals(expected, testScrabble.calculateScore("I"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_2() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 2;
        assertEquals(expected, testScrabble.calculateScore("D"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_3() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 3;
        assertEquals(expected, testScrabble.calculateScore("B"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_4() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 4;
        assertEquals(expected, testScrabble.calculateScore("F"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_5() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 5;
        assertEquals(expected, testScrabble.calculateScore("K"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_8() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 8;
        assertEquals(expected, testScrabble.calculateScore("J"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_10() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 10;
        assertEquals(expected, testScrabble.calculateScore("Q"));
    }

    @Test
    public void calculateScore_returnScoreForLetterValue_90() {
        Scrabble testScrabble = new Scrabble();
        Integer expected = 8;
        assertEquals(expected, testScrabble.calculateScore("WORD"));
    }
}
